# Generated by Django 3.1 on 2023-05-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='to_do_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sr_No', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
